//Source code generated by AppGPT (www.appgpt.tech)
import {
  Datagrid,
  List,
  EditButton,
  Edit,
  SimpleForm,
  Create,
  SelectColumnsButton,
  DatagridConfigurable,
  TopToolbar,
  CreateButton,
  ExportButton,
  FilterButton,
  //Field controls
  BooleanField,
  DateField,
  EmailField,
  ImageField,
  NumberField,
  ReferenceField,
  TextField,
  UrlField,
  //Input controls
  BooleanInput,
  DateInput,
  EmailInput,
  ImageInput,
  NumberInput,
  ReferenceInput,
  TextInput,
  UrlInput,
  PasswordInput,
} from 'react-admin';
import { useRecordContext } from 'react-admin';
import { Grid } from '@mui/material';
const ReadOnlyPasswordField = ({ record, source }) => {
  // You can customize the way you display the password here, e.g., mask it with asterisks
  const maskedPassword = '********';

  return <span>{maskedPassword}</span>;
};
const ListActions = () => (
  <TopToolbar>
    <FilterButton />
    <CreateButton />
    <ExportButton />
    <SelectColumnsButton />
  </TopToolbar>
);
const TasksTitle = () => {
  const record = useRecordContext();
  return <span>Tasks {record ? `"${record.description}"` : ''}</span>;
};

export const TasksList = () => (
  <List actions={<ListActions />} filters={ResourceFilters}>
    <DatagridConfigurable>
      <TextField source="description" />
      <ReferenceField source="runnerCurrentLocation" reference="Runners" />
      <TextField source="taskStatus" />
      <TextField source="pickupLocation" />
      <TextField source="deliveryLocation" />
      <DateField source="estimatedPickupTime" />
      <DateField source="estimatedDeliveryTime" />
      <TextField source="itemDescription" />
      <EditButton />
    </DatagridConfigurable>
  </List>
);

export const TasksEdit = () => (
  <Edit title={<TasksTitle />}>
    <SimpleForm>
      <Grid container rowSpacing={1} columnSpacing={{ xs: 1, sm: 2, md: 5 }}>
        <Grid item xs={4}>
          <TextInput source="description" />
        </Grid>
        <Grid item xs={4}>
          <ReferenceInput source="runnerCurrentLocation" reference="Runners" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="taskStatus" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="pickupLocation" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="deliveryLocation" />
        </Grid>
        <Grid item xs={4}>
          <DateInput source="estimatedPickupTime" />
        </Grid>
        <Grid item xs={4}>
          <DateInput source="estimatedDeliveryTime" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="itemDescription" />
        </Grid>
      </Grid>
    </SimpleForm>
  </Edit>
);

export const TasksCreate = () => (
  <Create>
    <SimpleForm>
      <Grid container rowSpacing={1} columnSpacing={{ xs: 1, sm: 2, md: 5 }}>
        <Grid item xs={4}>
          <TextInput source="description" />
        </Grid>
        <Grid item xs={4}>
          <ReferenceInput source="runnerCurrentLocation" reference="Runners" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="taskStatus" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="pickupLocation" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="deliveryLocation" />
        </Grid>
        <Grid item xs={4}>
          <DateInput source="estimatedPickupTime" />
        </Grid>
        <Grid item xs={4}>
          <DateInput source="estimatedDeliveryTime" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="itemDescription" />
        </Grid>
      </Grid>
    </SimpleForm>
  </Create>
);

const ResourceFilters = [
  <TextInput source="q" label="Search" alwaysOn />,
  ,
  <ReferenceInput
    source="runnerCurrentLocation"
    label="runnerCurrentLocation"
    reference="Runners"
    alwaysOn
  />,
  ,
  ,
  ,
  ,
  ,
  ,
];
